### ISSUE TITLE
Timing out issue with licenses

### ISSUE THREAD

**Issue by libby-barker** [humanmade/backupwordpress#1139]
These are timing out errors that seem related but affect multiple extensions. They might utilize cURL and be related to that. 

---

Here's the Dropbox issue over in the BackUpWordPress Pro Dropbox repo: https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34

---

Here's the Amazon issue over in the BackUpWordPress Pro S3 repo: 
https://github.com/humanmade/backupwordpress-pro-s3/issues/29

**Comment by sambulance** [comment]
Is this the issue @katmoody? https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34

**Comment by katmoody** [comment]
Yes @sambulance - updated original comment above with both current related issues.

**Comment by sambulance** [comment]
Paraphrased @katmoody from #1146:

> These tickets are still impacting users and starting to impact more users. I think they're related and they are a high priority to fix at this point.
>
> They need worked on asap and integrated into this/next sprint.

Please see tickets above. Seems the error is with curl.

@dashaluna @pdewouters @mikeselander @shadyvb Are any of you able to look at this ticket during this sprint please?

**Comment by sambulance** [comment]
Just had a quick look, the licence check is in this repo, which is in all the BWP Pro extensions: https://github.com/humanmade/backupwordpress-common

Looks like the actual call is using `wp_remote_get()`:
https://github.com/humanmade/backupwordpress-common/blob/master/CheckLicense.php#L189

Quite a few of the issues relate to timeout. Perhaps we could increase the `timeout` length? Googling some of the error messages received, perhaps we are sending an unexpected header/not explicitly setting a header? Not really sure here.

@katmoody It would be really useful if you could collate a list of the error messages you have got for this, with a reference to the initial ticket. Here are the ones I've seen:

- `cURL error 6: name lookup timed out` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/5821628291)
- `Failed connect to bwp.hmn.md:443; Operation now in progress` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/5943185360)
- `cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received` [Dasha #340](https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34#issuecomment-250498341)
- `502 bad gateway` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/6958280825)
- [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/7045016773) (@katmoody would be good to get an error message here)

**Comment by roborourke** [comment]
502 bad gateway errors are often fixed at the server level. It's happened before where for various reasons the headers returned from php-fpm were too big the fix was to change the nginx config to increase the buffer sizes and timeout.

In the location block where the other fastcgi params are set try adding the following. Perhaps one for @humanmade/servers?

```
fastcgi_read_timeout = 150;
fastcgi_buffers      = 16 16k;
fastcgi_buffer_size  = 32k;
```

**Comment by sambulance** [comment]
Thanks Rob - @humanmade/servers please can you help with this?

**Comment by owaincuvelier** [comment]
These are the current settings we have configured for our HM server, which the destination for the licence check request.

```
fastcgi_buffers 16 16k; 
fastcgi_buffer_size 32k;
fastcgi_read_timeout 7200;
```

In terms of debugging this further, ssh access to any of the ailed sites would be ideal. I'm not to confident in brain storming ideas about this issue, the only way I can be of assistance is I can just get in there an reverse engineer everything, and see what's happening.

**Comment by katmoody** [comment]
I might be able to get access to one of the sites in question for us ... if they get back to me I'll drop a note here asap. :D Thanks for weighing in @sambulance @roborourke and @owaincuvelier ... you guys all rock!

**Comment by katmoody** [comment]
Taking suggestion from @sambulance I'm re-listing the above tickets and revisiting them to ensure the errors are still occurring. 

- `cURL error 6: name lookup timed out` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/5821628291)
- `Failed connect to bwp.hmn.md:443; Operation now in progress` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/5943185360)
- `cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received` [Dasha #340](https://github.com/humanmade/backupwordpress-pro-dropbox/issues/34#issuecomment-250498341)
- `502 bad gateway` [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/6958280825)
- [Intercom](https://app.intercom.io/a/apps/7f1l4qyq/inbox/conversation/7045016773) (@katmoody would be good to get an error message here)

**Comment by libby-barker** [comment]
Hi @katmoody how did the testing with this go?

**Comment by katmoody** [comment]
@libby-barker - So far each of the folks who got back with me are still getting the same errors. Still no-one willing to grant full access. I'm technically on vacation this week but will try and send out messages again and see if I can find any other applicable errors/tickets.

**Comment by katmoody** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timing Out Issues with cURL errors](https://trello.com/c/2ty8Etzc/1-timing-out-issues-with-curl-errors)

**Comment by katmoody** [comment]
I'm closing this out unless I hear back from someone willing to provide access or am able to replicate locally - at this point I can't replicate the situation. 

This could also have been related to an EDD issue which didn't clear caching for license values - they pushed a release this past month and I haven't heard from anyone else having these kinds of issues in the past month. 

Closing unless we hear  back.

**Comment by katmoody** [comment]
Apparently this is still occurring so will reopen issue. I'm unsure if it's something we can fix or not.
